Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -9,21 +9,21 @@ jobs:
         run: |
           git clone https://github.com/liutingjieni/atop.git
           cd atop
-          if atop -V ; then echo "assert: atop have installed ";atop -V;fi
-          #sudo make && sudo make install
+          if atop -V ; then echo "assert: atop have installed "; exit;fi
+          sudo make && sudo make install
           echo '安装完成'
-      - name: subcmd_check
-        id: step_two
-        run: |
-          echo '测试'
-          if ! atop -V |grep -i Version; then echo "assert: atop -V error ";  atop -V; exit 1;fi
-          if ! atop -h |grep -i Usage; then echo "assert: atop -h error "; exit;fi
-          echo '测试'
+#       - name: subcmd_check
+#         id: step_two
+#         run: |
+#           echo '测试'
+#           if ! atop -V |grep -i Version; then echo "assert: atop -V error ";  atop -V; exit;fi
+#           if ! atop -h |grep -i Usage; then echo "assert: atop -h error "; atop -h; exit;fi
+#           echo '测试'
       - name: shadowfile_check
         id: step_three
         run: |
           echo '测试'
-          if ! ls -A /run/pacct_shadow.d/|wc -l; then echo "assert: shadowfile_check error "; exit;fi
+          if ! ls -A /run/pacct_shadow.d/|wc -l; then echo "assert: shadowfile_check error ";ls -A /run/pacct_shadow.d/; exit;fi
           echo '测试'
       - name: logfile_check
         id: step_four
