Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -30,13 +30,13 @@ jobs:
         run: |
           echo '测试'
           ls -l /var/log/atop/
-          if find  /var/log/atop/ -name "atop_*"|wc -l; then echo "assert: logfile_check error(/var/log/atop/) ";find  /var/log/atop/ -name \"atop_*\"； exit;fi
+          if ! find  /var/log/atop/ -name "atop_*"|wc -l; then echo "assert: logfile_check error(/var/log/atop/) ";find  /var/log/atop/ -name \"atop_*\"； exit;fi
           echo '测试'
       - name: atop_acctfile_check
         id: step_five
         run: |
           echo '测试'
-          if !ls /var/cache/atop.d/atop.acct|wc -l; then echo "assert: acctfile_check error(/var/cache/atop.d/atop.acct) ";ls /var/cache/atop.d/atop.acct; exit;fi
+          if ! ls /var/cache/atop.d/atop.acct|wc -l; then echo "assert: acctfile_check error(/var/cache/atop.d/atop.acct) ";ls /var/cache/atop.d/atop.acct; exit;fi
           echo '测试'
       - name: arg_check
         id: step_six
