Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -13,7 +13,7 @@ jobs:
           sudo make && sudo make install
           echo '安装完成'
           systemctl status atop.service
-          systemctl status atop-rotate.service
+          systemctl status atopacct.service
           systemctl status atop-rotate.timer
 #       - name: subcmd_check
 #         id: step_two
@@ -28,13 +28,13 @@ jobs:
 #           echo '测试'
 #           if ! ls -A /run/pacct_shadow.d/|wc -l; then echo "assert: shadowfile_check error ";ls -A /run/pacct_shadow.d/; exit;fi
 #           echo '测试'
-      - name: logfile_check
-        id: step_four
-        run: |
-          echo '测试'
-          ls -l /var/log/atop/
-          if ! find  /var/log/atop/ -name "atop_*"|wc -l; then echo "assert: logfile_check error(/var/log/atop/) ";find  /var/log/atop/ -name \"atop_*\"； exit;fi
-          echo '测试'
+#       - name: logfile_check
+#         id: step_four
+#         run: |
+#           echo '测试'
+#           ls -l /var/log/atop/
+#           if ! find  /var/log/atop/ -name "atop_*"|wc -l; then echo "assert: logfile_check error(/var/log/atop/) ";find  /var/log/atop/ -name \"atop_*\"； exit;fi
+#           echo '测试'
       - name: atop_acctfile_check
         id: step_five
         run: |
