Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -9,14 +9,14 @@ jobs:
         run: |
           git clone https://github.com/liutingjieni/atop.git
           cd atop
-          if atop -V ; then echo "assert: atop have installed ";fi
+          if atop -V ; then echo "assert: atop have installed ";atop -V;fi
           #sudo make && sudo make install
           echo '安装完成'
       - name: subcmd_check
         id: step_two
         run: |
           echo '测试'
-          if ! atop -V |grep -i Version; then echo "assert: atop -V error "; exit;fi
+          if ! atop -V |grep -i Version; then echo "assert: atop -V error ";  atop -V; exit 1;fi
           if ! atop -h |grep -i Usage; then echo "assert: atop -h error "; exit;fi
           echo '测试'
       - name: shadowfile_check
