Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -12,18 +12,18 @@ jobs:
           if atop -V ; then echo "assert: atop have installed "; exit;fi
           #sudo make && sudo make install
           echo '安装完成'
-      - name: subcmd_check
-        id: step_two
-        run: |
-          echo '测试'
-          if ! atop -V |grep -i Version; then echo "assert: atop -V error ";  atop -V; exit;fi
-          if ! atop -h |grep -i Usage; then echo "assert: atop -h error "; atop -h; exit;fi
-          echo '测试'
+#       - name: subcmd_check
+#         id: step_two
+#         run: |
+#           echo '测试'
+#           if ! atop -V |grep -i Version; then echo "assert: atop -V error ";  atop -V; exit;fi
+#           if ! atop -h |grep -i Usage; then echo "assert: atop -h error "; atop -h; exit;fi
+#           echo '测试'
       - name: shadowfile_check
         id: step_three
         run: |
           echo '测试'
-          if ! ls -A /run/pacct_shadow.d/|wc -l; then echo "assert: shadowfile_check error ";ls -A /run/pacct_shadow.d/; exit 1;fi
+          if ls -A /run/pacct_shadow.d/|wc -l; then echo "assert: shadowfile_check error ";ls -A /run/pacct_shadow.d/; exit 1;fi
           echo '测试'
       - name: logfile_check
         id: step_four
@@ -35,7 +35,7 @@ jobs:
         id: step_five
         run: |
           echo '测试'
-          if ! ls /var/cache/atop.d/atop.acct|wc -l; then echo "assert: acctfile_check error(/var/cache/atop.d/atop.acct) "; exit;fi
+          if ls /var/cache/atop.d/atop.acct|wc -l; then echo "assert: acctfile_check error(/var/cache/atop.d/atop.acct) "; exit;fi
           echo '测试'
       - name: arg_check
         id: step_six
@@ -43,10 +43,4 @@ jobs:
           echo '测试'
           if ! grep -i loginterval=10 /usr/share/atop/atop.daily; then echo "assert: arg_check error(loginterval=10 /usr/share/atop/atop.daily)"; exit;fi
           echo '测试'
-      - name: Set selected color
-        run: echo '::set-output name=SELECTED_COLOR::green'
-        id: random-color-generator
-      - name: Get color
-        run: echo "::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
-          
           
